// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.tag;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Tag.Create command logic.
 */
@Component("(tag_Create)")
public class CreateLogic implements ICreateLogic {
    /**
     * Verifies the Tag.Create command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new TagEvent.TagCreated events
     * @param tagState The current state of the Tag aggregate
     * @param name 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Tag
     */
    public TagEvent.TagCreated verify(java.util.function.Supplier<TagEvent.TagCreated> eventFactory, TagState tagState, String name, VerificationContext verificationContext) {
        TagEvent.TagCreated e = eventFactory.get();
        // TODO: implement
        return e;
    }

    @Override
    public TagState mutate(TagState tagState, String name, MutationContext<TagState, TagState.MutableTagState> mutationContext) {
        return null;
    }

}
