// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.tag;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Tag.Create command logic.
 */
@Component
public class CreateLogic implements ICreateLogic {
    /**
     * Verifies the Tag.Create command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new TagEvent.TagCreated events
     * @param tagState The current state of the Tag aggregate
     * @param name 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Tag
     */
    public TagEvent.TagCreated verify(java.util.function.Supplier<TagEvent.TagCreated> eventFactory, TagState tagState, String name, VerificationContext verificationContext) {
        TagEvent.TagCreated e = eventFactory.get();
        // TODO: implement
        return e;
    }

    /**
     * Performs the state mutation operation of Tag.Create command.
     * Creates a mutable copy of the state, updates it with the new body text,
     * and returns the new state.
     * 
     * @param tagState The current immutable state of the Tag
     * @param name 
     * @param aptosEventVersion 
     * @param aptosEventSequenceNumber 
     * @param aptosEventType 
     * @param aptosEventGuid 
     * @param status 
     * @param mutationContext The context that provides functionality including creating mutable state
     * @return The new state of the Tag
     */
    public TagState mutate(TagState tagState, String name, BigInteger aptosEventVersion, BigInteger aptosEventSequenceNumber, String aptosEventType, AptosEventGuid aptosEventGuid, String status, MutationContext<TagState, TagState.MutableTagState> mutationContext) {
        TagState.MutableTagState s = mutationContext.createMutableState(tagState);
        // TODO: implement
        return s; // Return the updated state
    }
}
