// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.article;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Article.Create command logic.
 */
@Component("(article_Create)")
public class CreateLogic implements ICreateLogic {
    /**
     * Verifies the Article.Create command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new ArticleEvent.ArticleCreated events
     * @param articleState The current state of the Article aggregate
     * @param title 
     * @param body 
     * @param owner 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Article
     */
    public ArticleEvent.ArticleCreated verify(java.util.function.Supplier<ArticleEvent.ArticleCreated> eventFactory, ArticleState articleState, String title, String body, String owner, VerificationContext verificationContext) {
        ArticleEvent.ArticleCreated e = eventFactory.get();
        // TODO: implement
        return e;
    }

    @Override
    public ArticleState mutate(ArticleState articleState, String title, String body, String owner, MutationContext<ArticleState, ArticleState.MutableArticleState> mutationContext) {
        return null;
    }

}
