// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.article;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Article.Delete command logic.
 */
@Component("(article_Delete)")
public class DeleteLogic implements IDeleteLogic {
    /**
     * Verifies the Article.Delete command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new ArticleEvent.ArticleDeleted events
     * @param articleState The current state of the Article aggregate
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Article
     */
    public ArticleEvent.ArticleDeleted verify(java.util.function.Supplier<ArticleEvent.ArticleDeleted> eventFactory, ArticleState articleState, VerificationContext verificationContext) {
        ArticleEvent.ArticleDeleted e = eventFactory.get();
        // TODO: implement
        return e;
    }

    @Override
    public ArticleState mutate(ArticleState articleState, MutationContext<ArticleState, ArticleState.MutableArticleState> mutationContext) {
        return null;
    }
}
