// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.article;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import java.math.BigInteger;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Article.UpdateComment command logic.
 */
@Component("(article_UpdateComment)")
public class UpdateCommentLogic implements IUpdateCommentLogic {
    /**
     * Verifies the Article.UpdateComment command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new ArticleEvent.CommentUpdated events
     * @param articleState The current state of the Article aggregate
     * @param commentSeqId 
     * @param commenter 
     * @param body 
     * @param owner 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Article
     */
    public ArticleEvent.CommentUpdated verify(java.util.function.Supplier<ArticleEvent.CommentUpdated> eventFactory, ArticleState articleState, BigInteger commentSeqId, String commenter, String body, String owner, VerificationContext verificationContext) {
        ArticleEvent.CommentUpdated e = eventFactory.get();
        // TODO: implement
        return e;
    }

    @Override
    public ArticleState mutate(ArticleState articleState, BigInteger commentSeqId, String commenter, String body, String owner, MutationContext<ArticleState, ArticleState.MutableArticleState> mutationContext) {
        return null;
    }

}
