// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.article;

import java.math.*;
import java.util.*;
import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Article.Update command logic.
 */
@Component("(article_Update)")
public class UpdateLogic implements IUpdateLogic {
    /**
     * Verifies the Article.Update command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new ArticleEvent.ArticleUpdated events
     * @param articleState The current state of the Article aggregate
     * @param title 
     * @param body 
     * @param owner 
     * @param tags 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Article
     */
    public ArticleEvent.ArticleUpdated verify(java.util.function.Supplier<ArticleEvent.ArticleUpdated> eventFactory, ArticleState articleState, String title, String body, String owner, String[] tags, VerificationContext verificationContext) {
        ArticleEvent.ArticleUpdated e = eventFactory.get();
        // TODO: implement
        return e;
    }

    @Override
    public ArticleState mutate(ArticleState articleState, String title, String body, String owner, String[] tags, MutationContext<ArticleState, ArticleState.MutableArticleState> mutationContext) {
        return null;
    }

}
