// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::add_tag_event {

    use aptos_blog_demo::article::{Self, AddTagEvent};
    use aptos_blog_demo::tag::Tag;
    use aptos_framework::object::Object;

    public fun id(add_tag_event: &AddTagEvent): address {
        article::add_tag_event_id(add_tag_event)
    }

    public fun tag(add_tag_event: &AddTagEvent): Object<Tag> {
        article::add_tag_event_tag(add_tag_event)
    }

}
