// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_example::aptos_blog_example_init {
    use aptos_blog_example::article;
    use aptos_blog_example::genesis_account;

    public entry fun initialize(account: &signer) {
        genesis_account::initialize(account);
        article::initialize(account);
    }

}
