// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::article_added_to_blog {

    use aptos_blog_demo::blog::{Self, ArticleAddedToBlog};

    public fun article_id(article_added_to_blog: &ArticleAddedToBlog): address {
        blog::article_added_to_blog_article_id(article_added_to_blog)
    }

}
