// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::article_updated {

    use aptos_blog_demo::article::{Self, ArticleUpdated};
    use aptos_blog_demo::tag::Tag;
    use aptos_framework::object::Object;
    use std::option::Option;
    use std::string::String;

    public fun id(article_updated: &ArticleUpdated): address {
        article::article_updated_id(article_updated)
    }

    public fun title(article_updated: &ArticleUpdated): String {
        article::article_updated_title(article_updated)
    }

    public fun body(article_updated: &ArticleUpdated): String {
        article::article_updated_body(article_updated)
    }

    public fun owner(article_updated: &ArticleUpdated): address {
        article::article_updated_owner(article_updated)
    }

    public fun tags(article_updated: &ArticleUpdated): Option<vector<Object<Tag>>> {
        article::article_updated_tags(article_updated)
    }

}
