// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::article_deleted {

    use aptos_blog_demo::article::{Self, ArticleDeleted};

    public fun article_id(article_deleted: &ArticleDeleted): address {
        article::article_deleted_id(article_deleted)
    }

}
