// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::blog_state_updated {

    use aptos_blog_demo::blog_state::{Self, BlogStateUpdated};

    public fun is_emergency(blog_state_updated: &BlogStateUpdated): bool {
        blog_state::blog_state_updated_is_emergency(blog_state_updated)
    }

    public fun articles(blog_state_updated: &BlogStateUpdated): vector<u128> {
        blog_state::blog_state_updated_articles(blog_state_updated)
    }

}
