// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::blog_created {

    use aptos_blog_demo::blog::{Self, BlogCreated};
    use std::string::String;

    public fun name(blog_created: &BlogCreated): String {
        blog::blog_created_name(blog_created)
    }

    public fun is_emergency(blog_created: &BlogCreated): bool {
        blog::blog_created_is_emergency(blog_created)
    }

}
