// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::blog_state_created {

    use aptos_blog_demo::blog_state::{Self, BlogStateCreated};

    public fun is_emergency(blog_state_created: &BlogStateCreated): bool {
        blog_state::blog_state_created_is_emergency(blog_state_created)
    }

}
