// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::donation_received {

    use aptos_blog_demo::blog::{Self, DonationReceived};

    public fun amount(donation_received: &DonationReceived): u64 {
        blog::donation_received_amount(donation_received)
    }

}
