// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::fa_donation_received {

    use aptos_blog_demo::blog::{Self, FaDonationReceived};

    public fun fa_amount(fa_donation_received: &FaDonationReceived): u64 {
        blog::fa_donation_received_fa_amount(fa_donation_received)
    }

}
