// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::init_fa_vault_event {

    use aptos_blog_demo::blog::{Self, InitFaVaultEvent};

    public fun metadata(init_fa_vault_event: &InitFaVaultEvent): address {
        blog::init_fa_vault_event_metadata(init_fa_vault_event)
    }

}
