// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::vault_withdrawn {

    use aptos_blog_demo::blog::{Self, VaultWithdrawn};

    public fun amount(vault_withdrawn: &VaultWithdrawn): u64 {
        blog::vault_withdrawn_amount(vault_withdrawn)
    }

}
