// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.blog;

import java.math.*;
import java.util.*;
import java.util.function.Supplier;

import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Blog.AddArticle command logic.
 */
@Component("(blog_AddArticle)")
public class AddArticleLogic implements IAddArticleLogic {

    @Override
    public BlogEvent.ArticleAddedToBlog verify(Supplier<BlogEvent.ArticleAddedToBlog> eventFactory, BlogState blogState, String articleId, VerificationContext verificationContext) {
        return null;
    }

    @Override
    public BlogState mutate(BlogState blogState, String articleId, MutationContext<BlogState, BlogState.MutableBlogState> mutationContext) {
        return null;
    }
}
