// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.test.aptosblogdemo.domain.blog;

import java.math.*;
import java.util.*;
import java.util.function.Supplier;

import org.test.aptosblogdemo.domain.*;
import org.test.aptosblogdemo.specialization.*;
import org.springframework.stereotype.Component;


/**
 * Implementation of the Blog.Create command logic.
 */
@Component("(blog_Create)")
public class CreateLogic implements ICreateLogic {

    @Override
    public BlogEvent.BlogCreated verify(Supplier<BlogEvent.BlogCreated> eventFactory, BlogState blogState, String name, Boolean isEmergency, VerificationContext verificationContext) {
        return null;
    }

    @Override
    public BlogState mutate(BlogState blogState, String name, Boolean isEmergency, MutationContext<BlogState, BlogState.MutableBlogState> mutationContext) {
        return null;
    }
}
